# Generated by Django 6.0.2 on 2026-03-04 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CLOTHING', 'Clothing'), ('KITCHEN', 'Kitchen Shopping'), ('VEGETABLES', 'Vegetables'), ('ELECTRONICS', 'Electronics'), ('RENT', 'Rent'), ('GROCERIES', 'Groceries'), ('MEDICAL', 'Medical'), ('TRAVEL', 'Travel'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Electricity/Water/Gas'), ('FUEL', 'Fuel'), ('INTERNET', 'Internet'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('NETBANKING', 'Net Banking')], default='CASH', max_length=20)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_added', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.family')),
            ],
        ),
    ]
