# Generated by Django 6.0.2 on 2026-03-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('CLOTHING', 'Clothing'), ('KITCHEN', 'Kitchen Shopping'), ('VEGETABLES', 'Vegetables'), ('ELECTRONICS', 'Electronics'), ('RENT', 'Rent'), ('DINING_OUT', 'Dining Out'), ('GROCERIES', 'Groceries'), ('MEDICAL', 'Medical'), ('TRAVEL', 'Travel'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('UTILITIES', 'Electricity/Water/Gas'), ('FUEL', 'Fuel'), ('INTERNET', 'Internet'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
